/* inicio do Script para popular a tabela FATOR_CALCULO, para teste iniciais */

INSERT INTO FATOR_CALCULO (ID, DIAS_ATRASO, MULTA, JUROS_DIA_ATRASO) VALUES (SEQ_FATOR_CALCULO.NEXTVAL, 1, 0.10, 2.00);
INSERT INTO FATOR_CALCULO (ID, DIAS_ATRASO, MULTA, JUROS_DIA_ATRASO) VALUES (SEQ_FATOR_CALCULO.NEXTVAL, 2, 0.10, 2.00);
INSERT INTO FATOR_CALCULO (ID, DIAS_ATRASO, MULTA, JUROS_DIA_ATRASO) VALUES (SEQ_FATOR_CALCULO.NEXTVAL, 3, 0.10, 2.00);
INSERT INTO FATOR_CALCULO (ID, DIAS_ATRASO, MULTA, JUROS_DIA_ATRASO) VALUES (SEQ_FATOR_CALCULO.NEXTVAL, 4, 0.20, 3.00);
INSERT INTO FATOR_CALCULO (ID, DIAS_ATRASO, MULTA, JUROS_DIA_ATRASO) VALUES (SEQ_FATOR_CALCULO.NEXTVAL, 5, 0.20, 3.00);
INSERT INTO FATOR_CALCULO (ID, DIAS_ATRASO, MULTA, JUROS_DIA_ATRASO) VALUES (SEQ_FATOR_CALCULO.NEXTVAL, 6, 0.30, 5.00);

/* fim do script para popular a tabela FATOR_CALCULO */