/* inicio do Script para popular a tabela FATOR_CALCULO, para teste iniciais */

INSERT INTO FATOR_CALCULO (DIAS_ATRASO, MULTA, JUROS_DIA_ATRASO) VALUES (1, 0.10, 2.00);
INSERT INTO FATOR_CALCULO (DIAS_ATRASO, MULTA, JUROS_DIA_ATRASO) VALUES (2, 0.10, 2.00);
INSERT INTO FATOR_CALCULO (DIAS_ATRASO, MULTA, JUROS_DIA_ATRASO) VALUES (3, 0.10, 2.00);
INSERT INTO FATOR_CALCULO (DIAS_ATRASO, MULTA, JUROS_DIA_ATRASO) VALUES (4, 0.20, 3.00);
INSERT INTO FATOR_CALCULO (DIAS_ATRASO, MULTA, JUROS_DIA_ATRASO) VALUES (5, 0.20, 3.00);
INSERT INTO FATOR_CALCULO (DIAS_ATRASO, MULTA, JUROS_DIA_ATRASO) VALUES (6, 0.30, 5.00);

/* fim do script para popular a tabela FATOR_CALCULO */